version: '3'
services:

  web:
    image: phalconphp/nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./src/:/src:rw
      - ./config/site.conf:/etc/nginx/conf.d/site.conf

  php:
    build: ./src/
    restart: always
    volumes:
      - ./src/phalcon:/src/phalcon:rw
      - ./src/composer.json:/src/composer.json:rw
#      - ./config/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - web